---
abstract: 'The DWIM Perl Debugger'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
  Test::Script: 1.02
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: pler
name: pler
no_index:
  directory:
    - inc
    - t
requires:
  Cwd: 3.00
  File::Find::Rule: 0.20
  File::Spec: 0.80
  File::Which: 0.05
  Getopt::Long: 0
  Probe::Perl: 0.01
  blib: 0
  perl: 5.00503
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/pler
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/pler
version: 1.05
