abstract: The DWIM Perl Debugger
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.47
  Test::Script: 0.01
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: pler
no_index: 
  directory: 
    - inc
    - t
requires: 
  Exporter: 0
  File::Find::Rule: 0.20
  File::Spec: 0.80
  File::Which: 0.05
  perl: 5.005
version: 0.16
